### PR TITLE
Add tab character coloring.

### PR DESCRIPTION
**Pull request by Teklad**
Just a small patch to color the tab character added in my notepadqq pull request.

### CODE REVIEW

**Comment by danieleds** [comment]
Is `.editor.show-tabs` in the style selector necessary? I'd avoid introducing a circular dependency.

**Comment by Teklad** [comment]
I suppose its not. I built in regex matching for that reason. I was in a
rush so I could get it finished. Lol. I'll polish that up. That would cover
everything wouldn't it?

**Comment by danieleds** [comment]
Yes, that would cover everything :)
The important thing is that CodeMirror and its plugins should not be aware of Notepadqq existence.

**Comment by danieleds** [comment]
To be clear, I'm referring to line 118 in show-invisibles.js

**Pull request merged**
